export const currencies = [
    { code: "USD", symbol: "$", name: "US Dollar" },
    { code: "EUR", symbol: "€", name: "Euro" },
    { code: "GBP", symbol: "£", name: "British Pound" },
    { code: "JPY", symbol: "¥", name: "Japanese Yen" },
    { code: "AUD", symbol: "A$", name: "Australian Dollar" },
    { code: "CAD", symbol: "C$", name: "Canadian Dollar" },
    { code: "INR", symbol: "₹", name: "Indian Rupee" },
    { code: "CNY", symbol: "¥", name: "Chinese Yuan" },
    { code: "CHF", symbol: "CHF", name: "Swiss Franc" },
    { code: "SEK", symbol: "kr", name: "Swedish Krona" },
    { code: "NZD", symbol: "NZ$", name: "New Zealand Dollar" },
    { code: "KRW", symbol: "₩", name: "South Korean Won" },
    { code: "SGD", symbol: "S$", name: "Singapore Dollar" },
    { code: "NOK", symbol: "kr", name: "Norwegian Krone" },
    { code: "MXN", symbol: "MX$", name: "Mexican Peso" },
    { code: "BRL", symbol: "R$", name: "Brazilian Real" },
    { code: "ZAR", symbol: "R", name: "South African Rand" },
    { code: "RUB", symbol: "₽", name: "Russian Ruble" },
    { code: "HKD", symbol: "HK$", name: "Hong Kong Dollar" },
    { code: "TRY", symbol: "₺", name: "Turkish Lira" },
    { code: "ILS", symbol: "₪", name: "Israeli New Shekel" },
    { code: "MYR", symbol: "RM", name: "Malaysian Ringgit" },
    { code: "THB", symbol: "฿", name: "Thai Baht" },
    { code: "IDR", symbol: "Rp", name: "Indonesian Rupiah" },
    { code: "PHP", symbol: "₱", name: "Philippine Peso" },
    { code: "CZK", symbol: "Kč", name: "Czech Koruna" },
    { code: "HUF", symbol: "Ft", name: "Hungarian Forint" },
    { code: "PLN", symbol: "zł", name: "Polish Zloty" },
    { code: "DKK", symbol: "kr", name: "Danish Krone" },
    { code: "AED", symbol: "د.إ", name: "United Arab Emirates Dirham" },
    { code: "SAR", symbol: "﷼", name: "Saudi Riyal" },
    { code: "EGP", symbol: "£", name: "Egyptian Pound" },
    { code: "NGN", symbol: "₦", name: "Nigerian Naira" },
    { code: "PKR", symbol: "₨", name: "Pakistani Rupee" },
    { code: "BDT", symbol: "৳", name: "Bangladeshi Taka" },
    { code: "LKR", symbol: "Rs", name: "Sri Lankan Rupee" },
    { code: "KZT", symbol: "₸", name: "Kazakhstani Tenge" },
    { code: "VND", symbol: "₫", name: "Vietnamese Dong" },
    { code: "UAH", symbol: "₴", name: "Ukrainian Hryvnia" },
    { code: "QAR", symbol: "﷼", name: "Qatari Rial" },
    { code: "KWD", symbol: "د.ك", name: "Kuwaiti Dinar" },
    { code: "BHD", symbol: "ب.د", name: "Bahraini Dinar" },
    { code: "OMR", symbol: "﷼", name: "Omani Rial" },
    { code: "JOD", symbol: "د.ا", name: "Jordanian Dinar" },
    { code: "MAD", symbol: "د.م.", name: "Moroccan Dirham" },
    { code: "TND", symbol: "د.ت", name: "Tunisian Dinar" },
    { code: "DZD", symbol: "د.ج", name: "Algerian Dinar" },
    { code: "XOF", symbol: "CFA", name: "West African CFA Franc" },
    { code: "XAF", symbol: "FCFA", name: "Central African CFA Franc" },
    { code: "GHS", symbol: "₵", name: "Ghanaian Cedi" },
    { code: "KES", symbol: "KSh", name: "Kenyan Shilling" },
    { code: "TZS", symbol: "TSh", name: "Tanzanian Shilling" },
    { code: "UGX", symbol: "USh", name: "Ugandan Shilling" },
    { code: "RWF", symbol: "FRw", name: "Rwandan Franc" },
    { code: "BWP", symbol: "P", name: "Botswana Pula" },
    { code: "MWK", symbol: "MK", name: "Malawian Kwacha" },
    { code: "ZMW", symbol: "ZK", name: "Zambian Kwacha" },
    { code: "MZN", symbol: "MT", name: "Mozambican Metical" },
    { code: "NAD", symbol: "N$", name: "Namibian Dollar" },
    { code: "BND", symbol: "B$", name: "Brunei Dollar" },
    { code: "FJD", symbol: "FJ$", name: "Fijian Dollar" },
    { code: "PGK", symbol: "K", name: "Papua New Guinean Kina" },
    { code: "SBD", symbol: "SI$", name: "Solomon Islands Dollar" },
    { code: "TOP", symbol: "T$", name: "Tongan Paʻanga" },
]